name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Publish artifact
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "-- Setting new release version ${NEW_VERSION} for ${REPO_NAME} --"
          mvn versions:set -B -DnewVersion="${NEW_VERSION}" -DprocessAllModules -DgenerateBackupPoms=false
          echo "-- Build, test and deploy release to GPR --"
          mvn clean deploy -B -s settings.xml -DskipTests
